sudo: required
services:
  - docker

before_install:
  - docker build -t aayushadhikari/react-test -f ./portfolio/Dockerfile.dev ./portfolio

script:
  - docker run -e CI=true aayushadhikari/react-test npm test

after_success:
  - docker build -t aayushadhikari/multi-portfolio ./portfolio
  - docker build -t aayushadhikari/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aayushadhikari/multi-portfolio
  - docker push aayushadhikari/multi-nginx
