sudo: required
services:
  - docker

before_install:
  - docker build -t aayushadhikari/personalsite -f Dockerfile.dev .

script:
  - docker run -e CI=true aayushadhikari/personalsite npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "personalsite"
  env: "Personalsite-env"
  bucket_name:
  bucket_path:
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
